### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kradosser** [f0nt4/TSLink#19]
Every time i upload the Plugin, this error happens:

http://prntscr.com/aq1xzw
(Yes i edited the config file and renamed it, i created a extra Teamspeak Query User and i created a database.)
Please help! :c

**Comment by f0nt4** [comment]
What do you mean by "i created a database"? You should point the plugin to the mybb database.

**Comment by kradosser** [comment]
oh.

**Comment by kradosser** [comment]
Still don't work, i edited the Database Information to the database i use for mybb. (Sorry for my bad english, hope you understand what i mean.)

**Comment by f0nt4** [comment]
What's the error message you're getting in the logs?
There is an php error but it's only showing in the logs.

**Comment by kradosser** [comment]
Solved it, thank you!
In config.php at line 35 with "$tslink_modcp_groups" i added more usergroups, but i used the wrong Brackets, ( instead of [.
