### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by UartigZone** [f0nt4/TSLink#21]
MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1366 - Incorrect integer value: '' for column 'tid' at row 1
Query:
INSERT INTO mybb_templates (`tid`,`title`,`template`,`sid`,`version`) VALUES ('','tslink_usercp_menu','\n<tr>\n<td class=\"tcat smalltext\">\n	<div class=\"expcolimage\">\n <img src=\"{$theme[\'imgdir\']}/collapse{$collapsedimg[\'usercptslink\']}.png\" id=\"usercptslink_img\" class=\"expander\" alt=\"[-]\" title=\"[-]\" />\n	</div>\n	<div>\n <span>\n	<strong>{$lang->tslink_menu_title}</strong>\n	</span>\n </div>\n</td>\n</tr>\n<tbody style=\"{$collapsed[\'usercptslink_e\']}\" id=\"usercptslink_e\">\n	<tr>\n	<td class=\"trow1 smalltext\">\n	<a href=\"usercp.php?action=tslink\" class=\"usercp_nav_item usercp_nav_tslink\">{$lang->tslink_menu_link}</a>\n </td>\n	</tr>\n</tbody>\n<style type=\"text/css\">\n.usercp_nav_tslink {\n	background: url(\'images/tslink/teamspeak3-icon.png\') no-repeat left center;\n}\n</style>','-2',1)
Please contact the MyBB Group for technical support.

What can i do at this point?

**Comment by f0nt4** [comment]
I really have no idea why this would be failling. The SQL query is fine.
Can you check if the tid column in your mybb_templates table is configured correctly?
Especially the auto_increment should part: http://i.imgur.com/iODFDZx.png
