### ISSUE TITLE
No way to enter TS3 UiD?

### ISSUE THREAD

**Issue by killkeeblerelves** [f0nt4/TSLink#22]
I have everything installed however I have no way of entering a UiD in the User Cp?

**Comment by f0nt4** [comment]
Hi killkeeblerelves, that's indeed not possible.
The way the plugin works is that it automatically finds your UIDs.
(And will succeed when you're visiting the forum and connecting to the TS server from the same computer.)
Simply go to your UserCP -> TeamSpeak Link and press the button.
If you really want to do it manually, you can add them directly in the database (mybb_tslink_uids table).

**Comment by killkeeblerelves** [comment]
I've tried the "teamspeak link button" it doesnt work. Check www.AwakenRP.com
I can send you the config file to verify

**Comment by f0nt4** [comment]
Please try the version attached. I added logging to the plugin which can be enabled/disable in the config file. Also upload the log folder and make sure it's writable for the webserver (chmod 777 or something).
After clicking on the button in the UserCP it should write a log file in the log folder.
You could sent me this file together with your config file to gianni@fonta.nl

[tslink1.3.5.zip](https://github.com/f0nt4/TSLink/files/505173/tslink1.3.5.zip)

**Comment by f0nt4** [comment]
Hi killkeeblerelves, 

did you solve the ip's being different? If so, could you tell us how?
Also I added a little tweak to the config.sample.php file to get the right ip when the board is behind cloudflare.

**Comment by killkeeblerelves** [comment]
I had to remove http proxy on cloud flare.

**Comment by killkeeblerelves** [comment]
Would be interesting to make the plugin reference a user entered ts3 UID.
As I still do not get requests upon sign up. Only on "update groups"

**Comment by f0nt4** [comment]
Ah ok! Well if you want it back, you could try to replace the following in your config:
```
if ($givenip == '')
{
	$givenip = $_SERVER['REMOTE_ADDR'];
	$mybb_ip = bin2hex(inet_pton($givenip));
}
else {
	$mybb_ip = bin2hex(inet_pton($givenip));	
}
```

To:

```
if ($givenip == '') {
    if (isset($_SERVER['HTTP_CF_CONNECTING_IP'])) {
        $givenip = $_SERVER['HTTP_CF_CONNECTING_IP'];
    } else {
        $givenip = $_SERVER['REMOTE_ADDR'];
    }
    $mybb_ip = bin2hex(inet_pton($givenip));
} else {
    $mybb_ip = bin2hex(inet_pton($givenip));
}
```

I'm not a big fan of letting users add their UID themselves, because if they would be a vip member, they could add someone else's UID to the database making them a VIP too.
After activation of someone's account the plugin should be triggered.
I don't know if you work with activation emails, but when users click the link, magic should start happening.
If you take a look in tslink.php you can see the hooks at the bottom.

In the future I'll probably check how MyBB is configured and build the hooks upon that.

**Comment by killkeeblerelves** [comment]
I've tried cf_connecting with no luck actually

**Comment by f0nt4** [comment]
Hmm, too bad. According to the CF support pages, this is the only way.
