### ISSUE TITLE
1366 - Incorrect integer value: '' for column 'tid' at row 1

### ISSUE THREAD

**Issue by troner18** [f0nt4/TSLink#25]
If I activate the plugin in the Admin CP I will get following error:

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
`1366 - Incorrect integer value: '' for column 'tid' at row 1`
Query:
`INSERT INTO mybb_templates (`tid`,`title`,`template`,`sid`,`version`) VALUES ('','tslink_usercp_menu','\n<tr>\n<td class=\"tcat smalltext\">\n <div class=\"expcolimage\">\n <img src=\"{$theme[\'imgdir\']}/collapse{$collapsedimg[\'usercptslink\']}.png\" id=\"usercptslink_img\" class=\"expander\" alt=\"[-]\" title=\"[-]\" />\n </div>\n    <div>\n <span>\n <strong>{$lang->tslink_menu_title}</strong>\n  </span>\n   </div>\n</td>\n</tr>\n<tbody style=\"{$collapsed[\'usercptslink_e\']}\" id=\"usercptslink_e\">\n    <tr>\n  <td class=\"trow1 smalltext\">\n <a href=\"usercp.php?action=tslink\" class=\"usercp_nav_item usercp_nav_tslink\">{$lang->tslink_menu_link}</a>\n   </td>\n </tr>\n</tbody>\n<style type=\"text/css\">\n.usercp_nav_tslink {\n  background: url(\'images/tslink/teamspeak3-icon.png\') no-repeat left center;\n}\n</style>','-2',1)`

Screenshot: [http://i.imgur.com/jkyNnaC.png](url) 
MySQL Version: 5.6.34

I'm sure that I configured the `config.php` right.

**Comment by f0nt4** [comment]
Sounds like the configuration of the mybb_templates is wrong. Please check if the tid column is auto increment and key for the table like this:
http://i.imgur.com/vzHbSDJ.png

**Comment by IllMakeUSquirtle** [comment]
I am having the exact same issue as above. Here is my config for the mybb_templates

https://gyazo.com/7510fc7798875524052dd26babc6d3b6

From what I can tell it's the same as the screenshot you have posted.

I am sure that I configured the config.php right as well.

Thanks in advance!

**Comment by fonta** [comment]
Fixed! https://github.com/f0nt4/TSLink/commit/de1a655840049347769b51bbe47d0273926daea3
