### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by fatboi615** [f0nt4/TSLink#4]
Every time i try this plugin i get this error, 
"Fatal error: Call to a member function fetch_array() on a non-object in C:\xampp\htdocs\inc\plugins\tslink\tslinkfunctions.php on line 282"
The line is about my table name but i changed it in the config and it still does not work please help me.

**Comment by fatboi615** [comment]
$table = 'phpbb_users';   - this is in the conf file
$mybb_user = $mybb_users->fetch_array(MYSQLI_ASSOC); - Line of the Error Called

**Comment by f0nt4** [comment]
The error is about not getting back any results.
Why did you change it to "phpbb_users"?
This plugin doesn't work with phpbb, only with MyBB!

**Comment by fatboi615** [comment]
i will try and change it back.
I thought it had to call youre user table mine was not called mybb_users but phpbb_users.
i will try it again. the templet i used the mybb installer, idk how it got like this

**Comment by fatboi615** [comment]
After looking at my db again i do have mybb_users, that was my mistake for doing this at 4am lol im going to try it again and post if i have an issue

**Comment by fatboi615** [comment]
ok i set everything again and still this error 
"Fatal error: Call to a member function fetch_array() on a non-object in C:\xampp\htdocs\inc\plugins\tslink\tslinkfunctions.php on line 282"
http://prntscr.com/5pn0f2  - screenshot of my conf file. 
any help would be awesome, i followed your tutorial part for part and nothing still .
