### ISSUE TITLE
Not showing any menu

### ISSUE THREAD

**Issue by thexhq** [f0nt4/TSLink#9]
I have installed version 1.2. I have no menus. Also, activated all parts in the configuration. Everything says installation successfully. I tested it 10 times or more with reinstalling the plugin, using older version deactivate/active. Nothing helped. I am sure to do everything right.
Any Ideas?

**Comment by f0nt4** [comment]
Can you check if the templates are created? Like these? http://puu.sh/mHgJE/41bdd51b0f.png

**Comment by thexhq** [comment]
Ok I checked. No templates there. What should I do?

**Comment by f0nt4** [comment]
Can you send me a temporary admin account on gianni@fonta.nl? I'll take a look.

**Comment by f0nt4** [comment]
After deleting the templates group manually and re-installing/activating the plugin the templates were created, but still no menu items showed up.
After research $mybb was undefined at the place where the hooks are activated.
I placed this portion of code in a function and added the $mybb and $plugins globals.
Directly after that the function is called and sorted things out.
